name: GitHub Actions Demo
on: [push]
jobs:
  job1:
    outputs:
      matrix: ${{ steps.hello.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Test JS action # Run the JavaScript action to output an array of objects.
        id: hello
        uses: ghusername/myreponame@master

  # Run the second job here, to read in the output of the previous job, set its value to a matrix, then iterate over that matrix.
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "I want to outputted objects from job1 to print here"
