 on:
  push:
     branches: [ main ] 
  pull_request:
     branches: [ main ] 
    
                       
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute sql files
        run: |
           
            t="one,two,three"
              a=($(echo "$t" | tr ',' '\n'))
             echo "${a[2]}"
 
            a=1
            echo "Display All SQL Files to be modified"
            #ls -la ./ChangeScript
            for f in ./ChangeScript/0$a*.sql; 
            do 
            if [ $a == 3 ]
             then
                 break
             fi
              echo Processing $f ; 
              echo Execute sqlcmd $(cat $f) ;
              echo i: $a
              ((a++))
            done;



