name: "cicd build and deploys"
on: ["pull_request","push","workflow_dispatch"]

env:
  AZURE_WEBAPP_NAME: 'WebAppTest65'
  AZURE_WEBAPP_PACKAGE_PATH: './myapp'
  DOTNET_VERSION: '5.0' 
  #NETCORE_VERSION: '5.0.x'
  SUBSCRIPTION_ID: '8505c722-0a5d-4d6e-9f33-650d1b85244b'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
     
      - name: array
        id: arr
        run: |
          arr=()
          for i in "$(./.sql)"
          do
           echo ::${i} 
           
    
          done
         
