 on:
  push:
     branches: [ main ] 
  pull_request:
     branches: [ main ] 
    
                       
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Maven
        run: |
            cat /etc/*-release
            
 
         
            echo "Display All SQL Files to be modified"
            ls -la ./ChangeScript
            for f in ./ChangeScript/*.sql; 
            do 
              echo Processing $f ; 
              echo Execute sqlcmd $(cat $f) ;
            done;



