 on:
  push:
     branches: [ main ] 
  pull_request:
     branches: [ main ] 
    
                       
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute sql files
        run: |
           
            
 
            #a=1
            echo "Display All SQL Files to be modified"
            #ls -la ./ChangeScript
            for f in ./ChangeScript/*.sql; 
            do 
            aa=($(echo "$f" | tr '.' '\n'))
            aaa=($(echo "$f" | tr '/' '\n'))
            echo "${aaa[1]}"
            if [ ${aaa[1]} == 03 ]
             then

                 echo Processing $f ; 
                 echo Execute sqlcmd $(cat $f) ;
             fi
             
            done;



