 on:
  push:
     branches: [ main ] 
  pull_request:
     branches: [ main ] 
    
                       
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute sql files
        run: |
           
            
 
            a=0
            echo "Display All SQL Files to be modified"
            #ls -la ./ChangeScript
            for f in ./ChangeScript/*.sql; 
            do 
            if [ $a == 3 ]
             then
                 break
             fi
              echo Processing $f ; 
              echo Execute sqlcmd $(cat $f) ;
              echo i: $a
              ((a++))
            done;



