on:
  push:
     branches: [ main ] 
  pull_request:
     branches: [ main ] 
                          

jobs: 
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Modified Files
        id: files
        run: |
            git diff-tree -r --no-commit-id --name-only --diff-filter=ACMRT ${{ steps.git_details.outputs.previous_commit }} ${{ steps.git_details.outputs.merge_commit }} | sed 's/:/\t/g' | cut -f 2 | grep $DEPLOYMENT_SCRIPT_FOLDER | sort -n > changed_file_list.txt
            cat changed_file_list.txt
      - name: Get Deployment Version & Format Files
        id: format
        run: |
          mkdir deployment_scripts
          version=$(python3 ./PythonCicdScripts/cicd_get_version.py)
          echo "Version of deployment is ${version} "
          i=1
          while read FILE; 
          do 
            wc_file_list=$(cat changed_file_list.txt | wc -l)
            if [[ ${FILE} == *.sql ]]; 
            then
                 file_name=`echo ${FILE} | sed 's|.*/||'`
                 cp ${FILE} ./deployment_scripts/V${version}.${i}__${file_name}
                 #echo cp ${FILE} ./deployment_scripts/V${version}.${i}__${file_name}
                 i=$(( ${i} + 1 ))
            fi
          done < changed_file_list.txt
          ls  ./deployment_scripts
