 on:
  push:
     branches: [ main ] 
  pull_request:
     branches: [ main ] 
    
    
 jobs:
   deploy-db-scripts:
    runs-on: ubuntu-latest
       steps:
      - uses: actions/checkout@v2
 
            ls -la ./ChangeScript
            for f in ./ChangeScript/*.sql; 
            do 
              echo Processing $f ; 
              echo Execute sqlcmd $(cat $f) ;
            done;

